export const LOAD_SUPPLIERS_SUCCESS = 'LOAD_SUPPLIERS_SUCCESS'

export const LOAD_ISSUES_IS_LOADING = 'LOAD_ISSUES_IS_LOADING'
export const LOAD_ISSUES_SUCCESS = 'LOAD_ISSUES_SUCCESS'
export const LOAD_ISSUES_HAS_ERRORED = 'LOAD_ISSUES_HAS_ERRORED'

export const CHANGE_MAIN_ISSUE = 'CHANGE_MAIN_ISSUE'